-- Online Shopping System — DDL
-- Owner: Nayudu Veera Hasini (25B11AI833) | Status: Not Started
--
-- CREATE TABLE statements for all 6 entities with:
--   * PRIMARY KEY (AUTO_INCREMENT) on every table
--   * UNIQUE on Customer.email
--   * NOT NULL on mandatory fields (customer_name, product_name, order_date, quantity, ...)
--   * FOREIGN KEY: Order->Customer, Order_Item->Order/Product, Payment->Order, Shipping->Order
--   * CHECK (price >= 0), CHECK (stock_quantity >= 0), CHECK (quantity > 0)
--   * DEFAULT 'Pending' on Order.order_status and Shipping.shipping_status
--
-- NOTE: `Order` is a reserved word in MySQL — quote it with backticks.
