-- Online Shopping System — DML
-- Owner: Murugu Amrutha Varshini (25B11AI779) | Status: Not Started
--
-- Sample data:
--   * INSERT customers (names, emails, phone numbers, addresses)
--   * INSERT products (category, price, stock quantity, descriptions)
--   * INSERT orders (order dates, totals, status)
--   * INSERT order_items matching the orders above (quantity, unit_price)
--   * INSERT payments and shipping records matching the orders
-- Plus UPDATE examples (order/payment/shipping status) and DELETE examples
-- (cancelled records).
